### ISSUE TITLE
启动不起来

### ISSUE THREAD

**Issue by zzmkj** [cdhaichuang/haichuangframework#2]
![image](https://user-images.githubusercontent.com/42564027/144179972-dbbc7506-5b85-41c4-b6e4-10371521b0ad.png)

**Comment by cdhaichuang** [comment]
启动前请执行初始化脚本，在根目录执行"java Init 项目代号 项目端口"，项目代号格式为驼峰式命名+序号，例如“java Init Test01 10001”
